import type { FactionId } from '@/types/faction';

export interface TrainingBattle {
  gameId: string;
  round: number;
  territory: string;
  attackerFaction: FactionId;
  defenderFaction: FactionId;
  attackerTroops: number;
  defenderTroops: number;
  attackerSpice: number;
  defenderSpice: number;
  attackerLeader: string;
  defenderLeader: string;
  attackerLeaderValue: number;
  defenderLeaderValue: number;
  knownTraitorRisk: boolean;
  attackerAlliance: FactionId[];
  defenderAlliance: FactionId[];
  /** Probabilité historique attaquant gagnant (0..1) — utilisée comme cible kNN */
  battleValue: number;
  winner: FactionId;
}

// 25 batailles historiques utilisées comme base de cas pour le simulateur Mentat.
export const BATTLE_TRAINING_DATASET: TrainingBattle[] = [
  { gameId: 'GAME_001', round: 3, territory: 'Arrakeen', attackerFaction: 'atreides', defenderFaction: 'harkonnen', attackerTroops: 12, defenderTroops: 8, attackerSpice: 9, defenderSpice: 18, attackerLeader: 'Jessica', defenderLeader: 'Feyd', attackerLeaderValue: 5, defenderLeaderValue: 6, knownTraitorRisk: true, attackerAlliance: ['fremen'], defenderAlliance: ['emperor'], battleValue: 0.83, winner: 'atreides' },
  { gameId: 'GAME_002', round: 6, territory: 'Carthag', attackerFaction: 'emperor', defenderFaction: 'fremen', attackerTroops: 14, defenderTroops: 16, attackerSpice: 24, defenderSpice: 4, attackerLeader: 'Fenring', defenderLeader: 'Stilgar', attackerLeaderValue: 6, defenderLeaderValue: 7, knownTraitorRisk: false, attackerAlliance: ['guild'], defenderAlliance: ['atreides'], battleValue: 0.92, winner: 'emperor' },
  { gameId: 'GAME_003', round: 8, territory: 'Sietch Tabr', attackerFaction: 'guild', defenderFaction: 'atreides', attackerTroops: 11, defenderTroops: 9, attackerSpice: 17, defenderSpice: 3, attackerLeader: 'Guild Rep', defenderLeader: 'Thufir', attackerLeaderValue: 5, defenderLeaderValue: 5, knownTraitorRisk: true, attackerAlliance: ['emperor'], defenderAlliance: ['fremen'], battleValue: 0.97, winner: 'guild' },
  { gameId: 'GAME_004', round: 2, territory: "Tueks Sietch", attackerFaction: 'fremen', defenderFaction: 'harkonnen', attackerTroops: 10, defenderTroops: 6, attackerSpice: 2, defenderSpice: 11, attackerLeader: 'Stilgar', defenderLeader: 'Piter', attackerLeaderValue: 7, defenderLeaderValue: 3, knownTraitorRisk: false, attackerAlliance: [], defenderAlliance: ['emperor'], battleValue: 0.69, winner: 'fremen' },
  { gameId: 'GAME_005', round: 5, territory: 'Arrakeen', attackerFaction: 'atreides', defenderFaction: 'emperor', attackerTroops: 8, defenderTroops: 15, attackerSpice: 7, defenderSpice: 26, attackerLeader: 'Duncan', defenderLeader: 'Shaddam', attackerLeaderValue: 2, defenderLeaderValue: 6, knownTraitorRisk: false, attackerAlliance: ['fremen'], defenderAlliance: ['guild'], battleValue: 0.88, winner: 'emperor' },
  { gameId: 'GAME_006', round: 4, territory: 'Cielago', attackerFaction: 'bene_gesserit', defenderFaction: 'guild', attackerTroops: 7, defenderTroops: 9, attackerSpice: 13, defenderSpice: 10, attackerLeader: 'Alia', defenderLeader: 'Guild Rep', attackerLeaderValue: 5, defenderLeaderValue: 5, knownTraitorRisk: false, attackerAlliance: [], defenderAlliance: ['emperor'], battleValue: 0.58, winner: 'guild' },
  { gameId: 'GAME_007', round: 7, territory: 'Habbanya', attackerFaction: 'harkonnen', defenderFaction: 'fremen', attackerTroops: 16, defenderTroops: 12, attackerSpice: 19, defenderSpice: 3, attackerLeader: 'Rabban', defenderLeader: 'Otheym', attackerLeaderValue: 4, defenderLeaderValue: 5, knownTraitorRisk: true, attackerAlliance: ['emperor'], defenderAlliance: ['atreides'], battleValue: 0.86, winner: 'harkonnen' },
  { gameId: 'GAME_008', round: 1, territory: 'Polar Sink', attackerFaction: 'guild', defenderFaction: 'bene_gesserit', attackerTroops: 5, defenderTroops: 5, attackerSpice: 8, defenderSpice: 6, attackerLeader: 'Soo-Soo Sook', defenderLeader: 'Jessica', attackerLeaderValue: 2, defenderLeaderValue: 5, knownTraitorRisk: false, attackerAlliance: [], defenderAlliance: [], battleValue: 0.31, winner: 'bene_gesserit' },
  { gameId: 'GAME_009', round: 6, territory: 'Carthag', attackerFaction: 'atreides', defenderFaction: 'guild', attackerTroops: 13, defenderTroops: 7, attackerSpice: 5, defenderSpice: 14, attackerLeader: 'Thufir', defenderLeader: 'Esmar Tuek', attackerLeaderValue: 5, defenderLeaderValue: 5, knownTraitorRisk: false, attackerAlliance: ['fremen'], defenderAlliance: ['emperor'], battleValue: 0.74, winner: 'atreides' },
  { gameId: 'GAME_010', round: 9, territory: 'Arrakeen', attackerFaction: 'guild', defenderFaction: 'emperor', attackerTroops: 18, defenderTroops: 12, attackerSpice: 28, defenderSpice: 22, attackerLeader: 'Guild Rep', defenderLeader: 'Fenring', attackerLeaderValue: 5, defenderLeaderValue: 6, knownTraitorRisk: false, attackerAlliance: ['harkonnen'], defenderAlliance: [], battleValue: 0.98, winner: 'guild' },
  { gameId: 'GAME_011', round: 3, territory: 'Basin', attackerFaction: 'fremen', defenderFaction: 'atreides', attackerTroops: 9, defenderTroops: 11, attackerSpice: 1, defenderSpice: 10, attackerLeader: 'Jamis', defenderLeader: 'Jessica', attackerLeaderValue: 2, defenderLeaderValue: 5, knownTraitorRisk: false, attackerAlliance: [], defenderAlliance: [], battleValue: 0.51, winner: 'atreides' },
  { gameId: 'GAME_012', round: 5, territory: 'False Wall', attackerFaction: 'harkonnen', defenderFaction: 'guild', attackerTroops: 10, defenderTroops: 10, attackerSpice: 16, defenderSpice: 12, attackerLeader: 'Feyd', defenderLeader: 'Guild Rep', attackerLeaderValue: 6, defenderLeaderValue: 5, knownTraitorRisk: true, attackerAlliance: ['emperor'], defenderAlliance: [], battleValue: 0.67, winner: 'harkonnen' },
  { gameId: 'GAME_013', round: 4, territory: 'Imperial Basin', attackerFaction: 'emperor', defenderFaction: 'atreides', attackerTroops: 13, defenderTroops: 6, attackerSpice: 20, defenderSpice: 4, attackerLeader: 'Captain Aramsham', defenderLeader: 'Gurney', attackerLeaderValue: 5, defenderLeaderValue: 4, knownTraitorRisk: false, attackerAlliance: ['guild'], defenderAlliance: ['fremen'], battleValue: 0.81, winner: 'emperor' },
  { gameId: 'GAME_014', round: 8, territory: 'Sietch Tabr', attackerFaction: 'atreides', defenderFaction: 'bene_gesserit', attackerTroops: 7, defenderTroops: 5, attackerSpice: 2, defenderSpice: 15, attackerLeader: 'Paul', defenderLeader: 'Alia', attackerLeaderValue: 10, defenderLeaderValue: 5, knownTraitorRisk: true, attackerAlliance: ['fremen'], defenderAlliance: [], battleValue: 0.73, winner: 'atreides' },
  { gameId: 'GAME_015', round: 2, territory: 'Carthag', attackerFaction: 'emperor', defenderFaction: 'harkonnen', attackerTroops: 8, defenderTroops: 9, attackerSpice: 19, defenderSpice: 7, attackerLeader: 'Burseg', defenderLeader: 'Piter', attackerLeaderValue: 3, defenderLeaderValue: 3, knownTraitorRisk: false, attackerAlliance: [], defenderAlliance: [], battleValue: 0.49, winner: 'emperor' },
  { gameId: 'GAME_016', round: 10, territory: 'Arrakeen', attackerFaction: 'fremen', defenderFaction: 'guild', attackerTroops: 20, defenderTroops: 14, attackerSpice: 6, defenderSpice: 31, attackerLeader: 'Stilgar', defenderLeader: 'Guild Rep', attackerLeaderValue: 7, defenderLeaderValue: 5, knownTraitorRisk: false, attackerAlliance: ['atreides'], defenderAlliance: ['emperor'], battleValue: 1.0, winner: 'fremen' },
  { gameId: 'GAME_017', round: 7, territory: 'The Great Flat', attackerFaction: 'bene_gesserit', defenderFaction: 'fremen', attackerTroops: 6, defenderTroops: 13, attackerSpice: 14, defenderSpice: 5, attackerLeader: 'Mother Ramallo', defenderLeader: 'Chani', attackerLeaderValue: 5, defenderLeaderValue: 6, knownTraitorRisk: false, attackerAlliance: ['guild'], defenderAlliance: ['atreides'], battleValue: 0.65, winner: 'fremen' },
  { gameId: 'GAME_018', round: 5, territory: 'Rock Outcroppings', attackerFaction: 'atreides', defenderFaction: 'guild', attackerTroops: 9, defenderTroops: 8, attackerSpice: 11, defenderSpice: 13, attackerLeader: 'Gurney', defenderLeader: 'Tuek', attackerLeaderValue: 4, defenderLeaderValue: 5, knownTraitorRisk: false, attackerAlliance: ['fremen'], defenderAlliance: [], battleValue: 0.56, winner: 'atreides' },
  { gameId: 'GAME_019', round: 6, territory: 'Arrakeen', attackerFaction: 'harkonnen', defenderFaction: 'atreides', attackerTroops: 15, defenderTroops: 10, attackerSpice: 17, defenderSpice: 6, attackerLeader: 'Feyd', defenderLeader: 'Paul', attackerLeaderValue: 6, defenderLeaderValue: 10, knownTraitorRisk: true, attackerAlliance: ['emperor'], defenderAlliance: ['fremen'], battleValue: 0.91, winner: 'harkonnen' },
  { gameId: 'GAME_020', round: 3, territory: 'Wind Pass', attackerFaction: 'guild', defenderFaction: 'emperor', attackerTroops: 7, defenderTroops: 11, attackerSpice: 10, defenderSpice: 21, attackerLeader: 'Guild Rep', defenderLeader: 'Fenring', attackerLeaderValue: 5, defenderLeaderValue: 6, knownTraitorRisk: false, attackerAlliance: [], defenderAlliance: ['harkonnen'], battleValue: 0.46, winner: 'emperor' },
  { gameId: 'GAME_021', round: 9, territory: 'Carthag', attackerFaction: 'atreides', defenderFaction: 'guild', attackerTroops: 16, defenderTroops: 13, attackerSpice: 12, defenderSpice: 29, attackerLeader: 'Paul', defenderLeader: 'Guild Rep', attackerLeaderValue: 10, defenderLeaderValue: 5, knownTraitorRisk: false, attackerAlliance: ['fremen'], defenderAlliance: ['emperor'], battleValue: 0.96, winner: 'atreides' },
  { gameId: 'GAME_022', round: 4, territory: 'Bight of the Cliff', attackerFaction: 'bene_gesserit', defenderFaction: 'harkonnen', attackerTroops: 5, defenderTroops: 12, attackerSpice: 18, defenderSpice: 15, attackerLeader: 'Jessica', defenderLeader: 'Rabban', attackerLeaderValue: 5, defenderLeaderValue: 4, knownTraitorRisk: true, attackerAlliance: [], defenderAlliance: ['emperor'], battleValue: 0.57, winner: 'harkonnen' },
  { gameId: 'GAME_023', round: 7, territory: 'Imperial Basin', attackerFaction: 'fremen', defenderFaction: 'emperor', attackerTroops: 18, defenderTroops: 16, attackerSpice: 4, defenderSpice: 30, attackerLeader: 'Stilgar', defenderLeader: 'Shaddam', attackerLeaderValue: 7, defenderLeaderValue: 6, knownTraitorRisk: false, attackerAlliance: ['atreides'], defenderAlliance: ['guild'], battleValue: 0.93, winner: 'fremen' },
  { gameId: 'GAME_024', round: 2, territory: 'False Wall South', attackerFaction: 'atreides', defenderFaction: 'bene_gesserit', attackerTroops: 6, defenderTroops: 4, attackerSpice: 8, defenderSpice: 9, attackerLeader: 'Duncan', defenderLeader: 'Wanna', attackerLeaderValue: 2, defenderLeaderValue: 1, knownTraitorRisk: false, attackerAlliance: [], defenderAlliance: [], battleValue: 0.38, winner: 'atreides' },
  { gameId: 'GAME_025', round: 10, territory: 'Arrakeen', attackerFaction: 'guild', defenderFaction: 'fremen', attackerTroops: 22, defenderTroops: 18, attackerSpice: 34, defenderSpice: 7, attackerLeader: 'Guild Rep', defenderLeader: 'Stilgar', attackerLeaderValue: 5, defenderLeaderValue: 7, knownTraitorRisk: false, attackerAlliance: ['emperor'], defenderAlliance: ['atreides'], battleValue: 1.0, winner: 'guild' },
];
